// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJv34Vx8M7SEu4d1zbt3vBGs31E8OT5i0',
    appId: '1:727918173946:web:2eb7a9b308fe69af26f343',
    messagingSenderId: '727918173946',
    projectId: 'flutter-services-2bd36',
    authDomain: 'flutter-services-2bd36.firebaseapp.com',
    storageBucket: 'flutter-services-2bd36.firebasestorage.app',
    measurementId: 'G-4VJNBGQVNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgrP8QNttFD7GeWYUeQPPUeAFPFa_d34w',
    appId: '1:727918173946:android:6d026f780c03e06f26f343',
    messagingSenderId: '727918173946',
    projectId: 'flutter-services-2bd36',
    storageBucket: 'flutter-services-2bd36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCcFowptAurf2uiSkW8_94YIOP46kKE94',
    appId: '1:727918173946:ios:7feeaff1ad6e253526f343',
    messagingSenderId: '727918173946',
    projectId: 'flutter-services-2bd36',
    storageBucket: 'flutter-services-2bd36.firebasestorage.app',
    iosClientId: '727918173946-h3e9kkte0tr7rkk1st4226tma8avu08p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCcFowptAurf2uiSkW8_94YIOP46kKE94',
    appId: '1:727918173946:ios:7feeaff1ad6e253526f343',
    messagingSenderId: '727918173946',
    projectId: 'flutter-services-2bd36',
    storageBucket: 'flutter-services-2bd36.firebasestorage.app',
    iosClientId: '727918173946-h3e9kkte0tr7rkk1st4226tma8avu08p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJv34Vx8M7SEu4d1zbt3vBGs31E8OT5i0',
    appId: '1:727918173946:web:f96de257e8f8ee3c26f343',
    messagingSenderId: '727918173946',
    projectId: 'flutter-services-2bd36',
    authDomain: 'flutter-services-2bd36.firebaseapp.com',
    storageBucket: 'flutter-services-2bd36.firebasestorage.app',
    measurementId: 'G-QQWCFZHM59',
  );
}
